### PR TITLE
Performance improvements: cache expensive bcrypt operations

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
Some numbers:

- Calling the http://localhost:8080/Plone/@@ok view as anonymous: < 30ms
- Calling the http://localhost:8080/Plone/@@ok with dexterity.membrane master ~ 600 ms
- Calling the http://localhost:8080/Plone/@@ok with dexterity.membrane this branch ~ 300 ms (the first time) ~50ms the other times (when the cache is hot)

**Comment by ale-rt** [comment]
@agitator it seems that lately you have been using dexterity.membrane, can you confirm my findings and eventually release a new version on PyPI?

**Comment by jensens** [comment]
Lgtm

**Comment by agitator** [comment]
2.0.1 released

**Pull request merged**
