### PR TITLE
[WIP] Plone 5.2

### PR DESCRIPTION
**Pull request by thet**

### CODE REVIEW

**Comment by ale-rt** [comment]
Before merging this one I would merge https://github.com/collective/Products.membrane/pull/18 and use a released egg of Products.membrane.
Currently the PR buildout uses a git checkout of the https://github.com/collective/Products.membrane/pull/18 branch

**Comment by agitator** [comment]
https://github.com/plone/Products.CMFPlone/issues/2987
@thet @ale-rt does validation of the password on reset work for you?

**Comment by ale-rt** [comment]
Nope, I see:
```
Error setting password
Sorry, this appears to be an invalid request. Please make sure you copied the URL exactly as it appears in your email and that you entered your user name correctly.
```
Plone 5.2 + Python2.7

But I think this is solved by https://github.com/plone/Products.CMFPlone/pull/2982 right?

**Comment by agitator** [comment]
@ale-rt yes, before the mentioned fix

**Pull request merged**
