### PR TITLE
Fix for `AuthEncoding >= 5.0`

### LINKED ISSUE #69: Cannot login when `AuthEncoding` version >= 5
And ff you want to do `bin/instance adduser admin admin` you get a traceback:

```
Traceback (most recent call last):
  File "/Users/peterm/workspace/fischereiverband/parts/instance/bin/interpreter", line 333, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/Users/peterm/workspace/fischereiverband/eggs/Products.PlonePAS-7.0.0-py3.11.egg/Products/PlonePAS/pas.py", line 92, in _doAddUser
    retval = _old_doAddUser(login, password, roles, domains)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/fischereiverband/eggs/Products.PluggableAuthService-2.8.1-py3.11.egg/Products/PluggableAuthService/PluggableAuthService.py", line 916, in _doAddUser
    if useradder.doAddUser(login, password):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/fischereiverband/eggs/Products.PluggableAuthService-2.8.1-py3.11.egg/Products/PluggableAuthService/plugins/ZODBUserManager.py", line 228, in doAddUser
    self.addUser(login, login, password)
  File "/Users/peterm/workspace/fischereiverband/eggs/Products.PluggableAuthService-2.8.1-py3.11.egg/Products/PluggableAuthService/plugins/ZODBUserManager.py", line 286, in addUser
    self._user_passwords[user_id] = self._pw_encrypt(password)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/fischereiverband/eggs/Products.PluggableAuthService-2.8.1-py3.11.egg/Products/PluggableAuthService/plugins/ZODBUserManager.py", line 401, in _pw_encrypt
    if AuthEncoding.is_encrypted(password):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/fischereiverband/eggs/AuthEncoding-5.0-py3.11.egg/AuthEncoding/AuthEncoding.py", line 287, in is_encrypted
    for id, prefix, scheme in _getSortedSchemes():
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/fischereiverband/eggs/AuthEncoding-5.0-py3.11.egg/AuthEncoding/AuthEncoding.py", line 110, in _getSortedSchemes
    return sorted(_schemes, reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'bytes'
```

### PR DESCRIPTION
**Pull request by petschki**
fixes #69

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM.
I don't use this package currently though, so I won't merge.

**Review by ale-rt — CHANGES_REQUESTED** [review]
I think that this one is good for every Python 3 version.
So I would restore the compatibility with Plone 5.2.

What do you think @petschki?

As an alternative it would be cool to upgrade the major version and write something in the Readme that currently says:

https://github.com/collective/dexterity.membrane/blob/14df6d3a6ab1171e25048fda93edd0835ef09e23/README.rst?plain=1#L13

**Comment by petschki** [comment]
Yes I can do that, but the test setup for plone 5.2 with python 3.6 breaks, because of the requirements here: https://dist.plone.org/release/5.2-latest/requirements.txt ... since setuptools==59.7.0 py3.6 support was dropped ... @ale-rt I will not do any effort in setting up this here and restore plone 5.2 tests for py3.7 and py3.8 if ok for you

**Comment by ale-rt** [comment]
Sure! 
I wanted to add a note in the Changelog https://github.com/collective/dexterity.membrane/pull/70.
Then if you want you can release it as well :)

**Comment by petschki** [comment]
👍🏼 I'll merge that one also and release afterwards

**Pull request merged**
